shop/apps/accounts/urls.py
from django.urls import path
from .views import *

app_name="accounts"
urlpatterns = [
    path("register/",RegisterUserView.as_view(),name="register"),
    path("verify/",VerifyRegisterCodeView.as_view(),name="Verify"),
    path('login/',LoginUserView.as_view(),name="Login"),
    path('logout/',LogoutUserView.as_view(),name="Logout"),
    path('userpanel/',UserPanelView.as_view(),name="userpanel"),
    path('change_password/',ChangePasswordView.as_view(),name="change_password"),
    path('remember_password/',RemeberPasswordView.as_view(),name="remember_password"),
     path("show_last_orders/",show_last_orders,name="show_last_orders"),
    path("update_profile/",UpdateProfileView.as_view(),name="update_profile"),
    path("show_user_payments/",show_user_payments,name="show_user_payments"),
    path("return_to_shop_cart/<uuid:order_code>/",return_to_shop_cart,name="return_to_shop_cart"),
]

shop/apps/main/urls.py
from django.urls import path
from .views import index,contactus,SliderView
app_name="main"
urlpatterns = [
    path("",index,name="index"),
    path("contactus",contactus,name="contactus"),
    # path("test/",test_view,name='test_view')
    path('sliders/',SliderView.as_view(),name="sliders"),
    # path('error/',handler404)
]

shop/apps/search/urls.py
from django.urls import path
from .views import *

app_name = 'search'

urlpatterns = [
    path('',SearchResultsView.as_view(),name="search_view"),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("apps.main.urls",namespace="main")),
    path("accounts/",include("apps.accounts.urls",namespace="accounts")),
    path("products/",include("apps.products.urls",namespace="products")),
    path("orders/",include("apps.orders.urls",namespace="orders")),
    path("discounts/",include("apps.discounts.urls",namespace="discounts")),
    path("payments/",include("apps.payments.urls",namespace="payments")),
    path("warehouses/",include("apps.warehouses.urls",namespace="warehouses")),
    path("csf/",include("apps.comment_scoring_favorites.urls",namespace="csf")),
    path("search/",include("apps.search.urls",namespace="search")),
    path("test_api/",include("apps.test_api.urls",namespace="test_api")),
    
    
    path("ckeditor",include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


handler404 = "apps.main.views.handler404"

shop/templates/partials/footer.html
		<!-- site__footer -->
		<footer class="site__footer">
			<div class="site-footer">
				<div class="container">
					<div class="site-footer__widgets">
						<div class="row">
							<div class="col-12 col-md-6 col-lg-4">
								<div class="site-footer__widget footer-contacts">
									<h5 class="footer-contacts__title">تماس با ما</h5>

									<ul class="footer-contacts__contacts">
										<li><i class="footer-contacts__icon fas fa-globe-americas"></i>
											ملایر، خیابان شهدا</li>
										<li><i class="footer-contacts__icon fas fa-mobile-alt"></i>
											<span class="ltr_text">081-45231</span>
										</li>

									</ul>
								</div>
							</div>
							<div class="col-6 col-md-3 col-lg-2">
								<div class="site-footer__widget footer-links">
									<h5 class="footer-links__title">اطلاعات</h5>
									<ul class="footer-links__list">
										<li class="footer-links__item">
											<a href="" class="footer-links__link">درباره ما</a>
										</li>
										<li class="footer-links__item">
											<a href="" class="footer-links__link">تماس با ما</a>
										</li>
										<li class="footer-links__item">
											<a href="" class="footer-links__link">قوانین و مقررات</a>
										</li>
									</ul>
								</div>
							</div>
							<div class="col-6 col-md-3 col-lg-2">
								<div class="site-footer__widget footer-links">
									<h5 class="footer-links__title">حساب کاربری</h5>
									<ul class="footer-links__list">
										<li class="footer-links__item">
											<a href="login.html" class="footer-links__link">
												ورود
											</a>
										</li>
										<li class="footer-links__item">
											<a href="register.html" class="footer-links__link">
												ثبت نام
											</a>
										</li>
									</ul>
								</div>
							</div>
							<div class="col-12 col-md-12 col-lg-4">
								<div class="site-footer__widget footer-newsletter">
									<h5 class="footer-contacts__title">شبکه های</h5>
									<div class="footer-newsletter__text footer-newsletter__text--social">ما را در شبکه
										های اجتماعی دنبال کنید</div>
									<ul class="footer-newsletter__social-links">
										<li
											class="footer-newsletter__social-link footer-newsletter__social-link--facebook">
											<a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a>
										</li>
										<li
											class="footer-newsletter__social-link footer-newsletter__social-link--twitter">
											<a href="#" target="_blank"><i class="fab fa-twitter"></i></a>
										</li>
										<li
											class="footer-newsletter__social-link footer-newsletter__social-link--youtube">
											<a href="#" target="_blank"><i class="fab fa-youtube"></i></a>
										</li>
										<li
											class="footer-newsletter__social-link footer-newsletter__social-link--instagram">
											<a href="#" target="_blank"><i class="fab fa-instagram"></i></a>
										</li>
										<li class="footer-newsletter__social-link footer-newsletter__social-link--rss">
											<a href="#" target="_blank"><i class="fas fa-rss"></i></a>
										</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
					<div class="site-footer__bottom">


					</div>
				</div>
			</div>
		</footer>
		<!-- site__footer / end -->

shop/templates/partials/header.html
		<!-- desktop site__header -->
		<header class="site__header d-lg-block d-none">
			<div class="site-header">
				<!-- .topbar -->
				<div class="site-header__topbar topbar">
					<div class="topbar__container container">
						<div class="topbar__row">
							<div class="topbar__item topbar__item--link"><a class="topbar-link"
									href="about-us.html">درباره ما</a></div>
							<div class="topbar__item topbar__item--link"><a class="topbar-link"
									href="{% url "main:contactus" %}">تماس با من</a></div>
							<div class="topbar__spring"></div>
							<div class="topbar__item">
								<div class="topbar-dropdown">
									{% if user.is_authenticated %}
									<button class="topbar-dropdown__btn" type="button">
										<a href="{% url "accounts:userpanel" %}" class="topbar-link">پنل کاربری</a>
										<i class="fa fa-user"></i>
									</button>
									{% endif %}
								</div>
							</div>

						</div>
					</div>
				</div>

				<div class="site-header__middle container">
					<div class="site-header__logo">
						<a href="https://github.com/sorna-fast">
							<img style="width: 70%;" src="{{media_url}}/images/logo.png" alt="">
						</a>
					</div>
					<div class="site-header__search">
						<div class="search">
							<form class="search__form" action="{% url "search:search_view" %}">
								<input class="search__input" name="q" placeholder="جستجو از میان 10,000 محصول"
									aria-label="Site search" type="text" autocomplete="off">
								<button class="search__button" type="submit">
									<i class="fa fa-search"></i>
								</button>
								<div class="search__border"></div>
							</form>
						</div>
					</div>
					<div class="site-header__phone">
						<div class="site-header__phone-title">پشتیبانی</div>
						<div class="site-header__phone-number"><span class="ltr_text">081-45231</span></div>
					</div>
				</div>
				<!-- .topbar / end -->
				{% include "partials/navbar.html" %}
			</div>
		</header>
		<!-- desktop site__header / end -->

shop/templates/partials/messages.html
{% if messages %}
    {% for message in messages %}
        <h1 class="alert alert-{{message.tags}}">
            {{message}}
        </h1>
    {% endfor %}
{% endif %}