shop/apps/main/urls.py
from django.urls import path
from .views import index,contactus,SliderView
app_name="main"
urlpatterns = [
    path("",index,name="index"),
    path("contactus",contactus,name="contactus"),
    # path("test/",test_view,name='test_view')
    path('sliders/',SliderView.as_view(),name="sliders"),
    # path('error/',handler404)
]

shop/apps/products/urls.py
from django.urls import path
from .views import *

app_name="products"
urlpatterns = [
    path("cheapest_products/",get_cheapest_products,name="cheapest_products"),
    path("last_products/",get_last_products,name="last_products"),
    path('popular_products_group/',get_popular_product_groups,name="popular_products_group"),
    path("product_details/<slug:slug>/",ProductDetailView.as_view(),name="product_details"),
    path("related_product/<slug:slug>/",get_related_products,name="related_product"),
    path("product_groups/",ProductGroupsView.as_view(),name="product_groups"),
    path("product_of_group/<slug:slug>/",ProductsByGroupView.as_view(),name="product_of_group"),
    path("ajax_admin/",filter_value_for_feature,name='filter_value_for_feature'),
    path("product_groups_partial/",get_product_groups,name="product_groups_partial"),
    path('filtering_product_brands_partial/<slug:slug>',get_brands,name="filtering_product_brands_partial"),
    path('filtering_features_partial/<slug:slug>',get_features_for_filtre,name="filtering_features_partial"),
    path('compare_list/',ShowCompareListView.as_view(),name='compare_list'),
    path('compare_table/',compare_table,name='compare_table'),
    path('add_to_compare_list/',add_to_compare_list,name='add_to_compare_list'),
    path('delete_from_compare_list/',delete_from_compare_list,name='delete_from_compare_list'),
    path('status_of_compare_list/',status_of_compare_list,name='status_of_compare_list'),

]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("apps.main.urls",namespace="main")),
    path("accounts/",include("apps.accounts.urls",namespace="accounts")),
    path("products/",include("apps.products.urls",namespace="products")),
    path("orders/",include("apps.orders.urls",namespace="orders")),
    path("discounts/",include("apps.discounts.urls",namespace="discounts")),
    path("payments/",include("apps.payments.urls",namespace="payments")),
    path("warehouses/",include("apps.warehouses.urls",namespace="warehouses")),
    path("csf/",include("apps.comment_scoring_favorites.urls",namespace="csf")),
    path("search/",include("apps.search.urls",namespace="search")),
    path("test_api/",include("apps.test_api.urls",namespace="test_api")),
    
    
    path("ckeditor",include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


handler404 = "apps.main.views.handler404"

shop/templates/product_app/partials/brands.html
<div class="widget-filters__item">
    <div class="filter filter--opened" data-collapse-item>
        <button type="button" class="filter__title" data-collapse-trigger>برند
            <svg class="filter__arrow" width="12px" height="7px">
                <use xlink:href="images/sprite.svg#arrow-rounded-down-12x7"></use>
            </svg>
        </button>
        <div class="filter__body" data-collapse-content>
            <div class="filter__container">
                <div class="filter-list">
                    <div class="filter-list__list">

                        {% for brand in brands %}
                        <label class="filter-list__item"><span class="filter-list__input input-check">
                            <span class="input-check__body">
                                
                                <input id="item_{{brand.id}}" name="brand" value="{{brand.id}}" type="checkbox" class="input-check__input"> 


                                <span class="input-check__box"></span>
                                <svg class="input-check__icon" width="9px" height="7px">
                                <use xlink:href="images/sprite.svg#check-9x7"></use>
                                </svg>


                            </span>
                            </span><span class="filter-list__title">{{brand.brand_title}}</span>
                            <span class="filter-list__counter">{{brand.product_of_brands.all|length}}</span>
                        </label>
                        {% endfor %}
                            
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

shop/templates/product_app/partials/cheapest_products.html
<div class="block block-products-carousel" data-layout="grid-5">
    <div class="container">
        {% include "partials/products/root_group.html" with title="ارزان ترین محصولات" %}
        <div class="product-flexbox" style="">
            {% for product in products %}
            {% include "partials/products/product_box.html" with type=1 %}
            {% endfor %}
            </div>
        </div>
    </div>    

shop/templates/product_app/partials/compare_table.html
{% if products %}
    <div class="container">
        <h2 style="text-align: center; color: green;">کالا های انتخابی برای مقایسه</h2>
        <table class="table table-bordered">


            <tr style="background: #f1f1f1; text-align: center;">
                <th>ویژگی کالا / ویژگی</th>
                {% for product in products %}
                    <th>
                        <i class="fa fa-times product-remove" onclick="deleteFromCompareList({{product.id}})"></i>
                        {{product.product_name}}
                    </th>
                {% endfor %}
            </tr>


            {% for feature in features %}
                <tr>
                    <td style="font-size:1.2rem; font-weight:900; width:25%;">{{feature}}</td>
                    {% for product in products %}
                        <td style="text-align: center;">
                            {% for item in product.product_features.all %}
                                {% if item.feature == feature %}
                                    <span style="margin: 5px;">{{item.filter_value.value_title}}</span>
                                {% endif %}
                            {% endfor %}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>
{% else %}



        <div class="compare-empty">
            <div class="compare-empty__icon">
              <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                {% comment %} <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
                  d="M4 6h16M4 10h16M4 14h16M4 18h16" />
              </svg> {% endcomment %}
            </div>
            <h2 class="compare-empty__title">جدول مقایسه خالی است!</h2>
            <p class="compare-empty__desc">محصولات دلخواه خود را برای مقایسه انتخاب کنید.</p>

            <div class="compare-empty__icon swing-icon">
                <svg xmlns="http://www.w3.org/2000/svg" width="96" height="96" viewBox="0 0 640 512" fill="currentColor">
                  <path d="M528 448H352V153.25c20.6-8.9 35.6-27.7 39.2-50.25h73.5c-1.1 5.2-1.7 10.6-1.7 16 0 35.3 28.7 64 64 64s64-28.7 64-64c0-5.4-.6-10.8-1.7-16h25.7c8.8 0 16-7.2 16-16V80c0-8.8-7.2-16-16-16H464c-8.8 0-16 7.2-16 16v7.25h-73.5C369.6 64.9 354.6 46.1 334 37.25V32c0-17.7-14.3-32-32-32s-32 14.3-32 32v5.25C249.6 46.1 234.6 64.9 230.8 87.25H157.3V80c0-8.8-7.2-16-16-16H32c-8.8 0-16 7.2-16 16v7.25c0 8.8 7.2 16 16 16h25.7c-1.1 5.2-1.7 10.6-1.7 16 0 35.3 28.7 64 64 64s64-28.7 64-64c0-5.4-.6-10.8-1.7-16h73.5c3.6 22.55 18.6 41.35 39.2 50.25V448H112c-8.8 0-16 7.2-16 16v32c0 8.8 7.2 16 16 16h416c8.8 0 16-7.2 16-16v-32c0-8.8-7.2-16-16-16zM160 96c0 17.7-14.3 32-32 32s-32-14.3-32-32h64zm384 0c0 17.7-14.3 32-32 32s-32-14.3-32-32h64z"/>
                </svg>
              </div>
              

            <h6 style="background-color:pink; text-align: center; border-radius:30%;font-size: 18px; font-weight: 600; color: #777;">محصولی برای مقایسه انتخاب نشده است</h6> 
            <a href="{% url 'main:index' %}" class="btn-to-shop">رفتن به فروشگاه</a>
          </div>
          


{% endif %}

shop/templates/product_app/partials/features_filter.html
<div id="accordion">
    {% for key,value in feature_dict.items %}
    {% if value %}
    <div class="card" style="border: none; color:#868686;">
        <div class="card-header" style="padding:0 0 10px;">
          <a class="card-link" data-toggle="collapse" href="#collapseOne{{key.id}}" >
            <button type="button" class="filter__title" data-collapse-trigger style="color:#000;">
                {{key}}
               
                <svg class="filter__arrow" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="32" height="32" viewBox="0 0 256 256" xml:space="preserve">
                  <defs>
                  </defs>
                  <g style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: none; fill-rule: nonzero; opacity: 1;" transform="translate(1.4065934065934016 1.4065934065934016) " >
                    <path d="M 90 24.25 c 0 -0.896 -0.342 -1.792 -1.025 -2.475 c -1.366 -1.367 -3.583 -1.367 -4.949 0 L 45 60.8 L 5.975 21.775 c -1.367 -1.367 -3.583 -1.367 -4.95 0 c -1.366 1.367 -1.366 3.583 0 4.95 l 41.5 41.5 c 1.366 1.367 3.583 1.367 4.949 0 l 41.5 -41.5 C 89.658 26.042 90 25.146 90 24.25 z" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" transform=" matrix(1 0 0 1 0 0) " stroke-linecap="round" />
                  </g>
                  </svg>
            </button>
            
          </a>
        </div>
        <div id="collapseOne{{key.id}}" class="collapse" data-parent="#accordion">
          <div class="card-body" style="padding: 0;">
            {% for item in value %}
                <label class="filter-list__item"> 
                    <span class="filter-list__input input-check">
                        <span class="input-check__body">
                        <input id="item_{{item.id}}" name="feature" value="{{item.id}}" class="input-check__input" type="checkbox" /> 
                        <span class="input-check__box"></span>
                        <svg class="input-check__icon" width="9px" height="7px">
                            <use xlink:href="images/sprite.svg#check-9x7"></use>
                        </svg>
                        </span>
                    </span>
                    <span class="filter-list__title">{{item.value_title}}</span>
                </label>
            {% endfor %}
          </div>
        </div>
    </div>
    {% endif %}
    
{% endfor %}

</div> 

shop/templates/product_app/partials/last_products.html
<div class="block block-products-carousel" data-layout="grid-5">
    <div class="container">
        {% include "partials/products/root_group.html" with title="جدیدترین محصولات"%}
        <div class="product-flexbox" style="">
            {% for product in products %}
            {% include "partials/products/product_box.html" with type=2%}
            {% endfor %}
        </div>
    </div>
</div>    

shop/templates/product_app/partials/popular_product_group.html
  <div class="block block--highlighted block-categories block-categories--layout--compact">
    <div class="container">
      <div class="block-header">
        <h3 class="block-header__title">دسته های محبوب</h3>
        <div class="block-header__divider"></div>
      </div>
      <div class="block-categories__list">
        {% for group in product_group %}
            <div class="block-categories__item category-card category-card--layout--compact">
            <div class="category-card__body">
                <div class="category-card__image">
                <a href="{% url 'products:product_of_group' slug=group.slug %}">
                    <img src="{{media_url}}{{group.image_name}}" alt="" >
                </a>
                </div>
                <div class="category-card__content">
                <div class="category-card__name"><a href="{% url 'products:product_of_group' slug=group.slug %}">{{group.group_title}}</a></div>

                <div class="category-card__products">{{group.products_of_group.all|length}} محصول</div>
                </div>
            </div>
            </div>
        {% endfor %}
        <a href="{% url "products:product_groups" %}">همه</a>
          </div>
        </div>
      </div>
    </div>
  </div>

shop/templates/product_app/partials/product_groups.html
<ul class="filter-categories__list">
    {% for group in product_groups %}
    <li class="filter-categories__item filter-categories__item--parent" >
        <a href="{% url "products:product_of_group" slug=group.slug %}">{{group.group_title}}</a>
        <div class="filter-categories__counter">{{group.products_of_group.all|length}}</div>
    </li>
    {% endfor %}
</ul>

shop/templates/product_app/partials/related_products.html
<div class="block block-products-carousel" data-layout="grid-5">
    <div class="container">
        {% include "partials/products/root_group.html" with title="محصولات مرتبط"%}
        <div class="product-flexbox" style="">
            {% for product in related_product %}
                {% include "partials/products/product_box.html" with type=1 %}
            {% endfor %}
        </div>
    </div>
</div>    